---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: zsh
  import_tasks: zsh.yml
  tags:
    - zsh

- name: vim
  import_tasks: vim.yml
  tags:
    - vim
